# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Dekking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mateVanDekking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kernen', to='kernendekking_app.Domein')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_level_name_single', models.CharField(max_length=63)),
                ('sub_level_name_multiple', models.CharField(max_length=63)),
                ('short_name', models.CharField(max_length=7)),
                ('long_name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=1023)),
                ('super_level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level', to='kernendekking_app.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('long_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Vak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=7)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernendekking_app.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='domein',
            name='vak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domeinen', to='kernendekking_app.Vak'),
        ),
        migrations.AddField(
            model_name='dekking',
            name='bestaandeKern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dektInDekking', to='kernendekking_app.Kern'),
        ),
        migrations.AddField(
            model_name='dekking',
            name='gedekteKern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedektInDekking', to='kernendekking_app.Kern'),
        ),
        migrations.AddField(
            model_name='covering',
            name='covered_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered', to='kernendekking_app.Level'),
        ),
        migrations.AddField(
            model_name='covering',
            name='covering_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='kernendekking_app.Level'),
        ),
        migrations.AddField(
            model_name='covering',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernendekking_app.Measure'),
        ),
    ]
