# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernendekking_app', '0002_auto_20170506_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='level',
            name='full_name',
            field=models.CharField(default='NA', max_length=512),
            preserve_default=False,
        ),
    ]
