# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernendekking_app', '0003_auto_20170506_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='full_name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
